### ISSUE TITLE
Error While Executing NPM Start

### ISSUE THREAD

**Issue by shivamsouravjha** [shivamsouravjha/Meme_Yogi#3]
**D:\1ST ASSIGNMENT\Let-us-travel\Meme_Yogi\Meme_Yogi\node_modules\express\lib\router\route.js:202
        throw new Error(msg);
        ^

Error: Route.get() requires a callback function but got a [object Undefined]
    at Route.<computed> [as get] (D:\1ST ASSIGNMENT\Let-us-travel\Meme_Yogi\Meme_Yogi\node_modules\express\lib\router\route.js:202:15)
    at Function.proto.<computed> [as get] (D:\1ST ASSIGNMENT\Let-us-travel\Meme_Yogi\Meme_Yogi\node_modules\express\lib\router\index.js:510:19)
    at Object.<anonymous> (D:\1ST ASSIGNMENT\Let-us-travel\Meme_Yogi\Meme_Yogi\ROUTERS\memer.js:9:8)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\1ST ASSIGNMENT\Let-us-travel\Meme_Yogi\Meme_Yogi\server.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meme_yogi@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meme_yogi@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\91776\AppData\Roaming\npm-cache\_logs\2021-02-12T16_09_54_206Z-debug.log
PS D:\1ST ASSIGNMENT\Let-us-travel\Meme_Yogi\Meme_Yogi>**

**Comment by KaanGaming** [comment]
I proposed a few changes to the files inside. Only fixing coding errors, also there are only 2 issues I couldn't fix by myself and I think only you and other collaborators (if there are) can fix that.

**Comment by KaanGaming** [comment]
Please edit the getPlaceById function found in memercontroller.js. I made it empty just for you to edit some code in.

**Comment by shivamsouravjha** [comment]
Will look into it and edit accordingly.

**Comment by shivamsouravjha** [comment]
@KaanGaming while defining Schema in Mongo, if we use 'Username' instead of 'username' will it cause a trouble? because I'm facing it while doing so.
