### ISSUE TITLE
Sign-UP not working

### ISSUE THREAD

**Issue by shivamsouravjha** [shivamsouravjha/Meme_Yogi#6]
When I try to signup a new Memer at 'http://localhost:5000/api/memers/signup' ,I'm getting 'Signing up failed, please try again later.'

Which is for Try and Catch at signup of memercontrollers(line34-line 44).

When I remove the try block(to get exact error)

**(node:21380) UnhandledPromiseRejectionWarning: MongooseError: Operation `memers.findOne()` buffering timed out 
after 10000ms
    at Timeout.<anonymous> (D:\1ST ASSIGNMENT\Let-us-travel\Meme_Yogi\Meme_Yogi\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:185:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:21380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise 
rejections that are not handled will terminate the Node.js process with a non-zero exit code.**

To run this use  **npm install & send the request in postman**

**Comment by shivamsouravjha** [comment]
Ask it to be assigned before working.

**Comment by shivamsouravjha** [comment]
Apparently in #3 mongoose was assigned to be **mongodb** in server.js that led to the crash of program.
Updated.
